#!/usr/bin/env python3
"""
Sync developers.wazion.com content from WAzion capabilities.json.

Generates:
  - docs/tools-catalog.md (full tools table)
  - website/static/openapi.yaml (partial MCP OpenAPI spec)

Usage:
  python scripts/sync-from-capabilities.py <path-to-capabilities.json>
  python scripts/sync-from-capabilities.py -  # reads from stdin
"""

import json
import sys
import os
from datetime import datetime, timezone

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_capabilities(path):
    if path == '-':
        return json.load(sys.stdin)
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def generate_tools_catalog(caps):
    """Generate docs/tools-catalog.md from capabilities.json."""
    actions = caps.get('actions', {})
    categories = caps.get('categories', {})
    version = caps.get('version', '?')

    # Filter out hidden tools
    visible = {k: v for k, v in actions.items() if not v.get('mcp_hidden', False)}

    # Sort alphabetically by action name
    sorted_actions = sorted(visible.items(), key=lambda x: x[0])

    lines = []
    lines.append('<!-- AUTO-GENERATED-START — Do not edit between these markers. Content is regenerated by sync-public-docs workflow. -->')
    lines.append(f'# WAzion Tools Catalog')
    lines.append('')
    lines.append(f'> Auto-generated from `capabilities.json` v{version}')
    lines.append(f'> Total tools: {len(sorted_actions)} (excluding hidden)')
    lines.append('')
    lines.append('| Tool | Category | Type | Description |')
    lines.append('|------|----------|------|-------------|')

    for name, action in sorted_actions:
        cat_key = action.get('category', 'general')
        cat_name = categories.get(cat_key, {}).get('name', cat_key)
        action_type = action.get('type', 'query')
        desc = action.get('description', '')
        # Truncate long descriptions for table readability
        if len(desc) > 120:
            desc = desc[:117] + '...'
        # Escape pipe characters in description
        desc = desc.replace('|', '\\|')
        lines.append(f'| `{name}` | {cat_name} | {action_type} | {desc} |')

    lines.append('')
    lines.append('---')
    lines.append('')
    lines.append('See [OpenAPI spec](../openapi.yaml) for full parameter details.')
    lines.append('<!-- AUTO-GENERATED-END -->')
    lines.append('')

    return '\n'.join(lines)


def generate_openapi_yaml(caps):
    """Generate website/static/openapi.yaml (partial) from capabilities.json."""
    actions = caps.get('actions', {})
    categories = caps.get('categories', {})
    version = caps.get('version', '?')

    visible = {k: v for k, v in actions.items() if not v.get('mcp_hidden', False)}

    # Build tags from categories
    tag_lines = []
    for key, cat in sorted(categories.items()):
        tag_lines.append(f'  - name: {key}')
        tag_lines.append(f'    description: {cat.get("description", cat.get("name", key))}')

    # Build tool schemas for each action
    tool_schemas = []
    for name, action in sorted(visible.items()):
        cat = action.get('category', 'general')
        desc = action.get('description', '')
        action_type = action.get('type', 'query')
        params = action.get('params', {})

        # Build parameters schema
        props = {}
        required = []
        if isinstance(params, dict):
            for pname, pdef in params.items():
                prop = {}
                prop['type'] = pdef.get('type', 'string')
                if 'description' in pdef:
                    prop['description'] = pdef['description']
                if 'enum' in pdef:
                    prop['enum'] = pdef['enum']
                if 'default' in pdef:
                    prop['default'] = pdef['default']
                props[pname] = prop
                if pdef.get('required', False):
                    required.append(pname)

        tool_schemas.append({
            'name': name,
            'category': cat,
            'description': desc,
            'type': action_type,
            'properties': props,
            'required': required,
            'confirmation': action.get('confirmation_required', False),
        })

    # Generate YAML manually (no pyyaml dependency needed)
    lines = []
    lines.append('openapi: 3.1.0')
    lines.append('info:')
    lines.append('  title: WAzion API')
    lines.append('  description: |')
    lines.append('    WAzion is a WhatsApp Business automation and AI assistant platform. This API exposes')
    lines.append(f'    {len(visible)} tools via the Model Context Protocol (MCP) over JSON-RPC 2.0, allowing you to')
    lines.append('    manage every aspect of your WAzion dashboard programmatically.')
    lines.append('')
    lines.append('    ## Protocol')
    lines.append('')
    lines.append('    All requests use **JSON-RPC 2.0** over a single POST endpoint. The server implements')
    lines.append('    the MCP Streamable HTTP transport (spec 2025-03-26).')
    lines.append('')
    lines.append('    ## Authentication')
    lines.append('')
    lines.append('    Include your API token as a Bearer token in the `Authorization` header. You can find')
    lines.append('    your token in the WAzion Dashboard under **Settings**.')
    lines.append('')
    lines.append('    ## Quick Start')
    lines.append('')
    lines.append('    ```bash')
    lines.append("    curl -X POST https://www.wazion.com/api/mcp/ \\")
    lines.append('      -H "Content-Type: application/json" \\')
    lines.append('      -H "Authorization: Bearer YOUR_TOKEN" \\')
    lines.append("      -d '{\"jsonrpc\":\"2.0\",\"method\":\"tools/call\",\"params\":{\"name\":\"get_shop_status\",\"arguments\":{}},\"id\":1}'")
    lines.append('    ```')
    lines.append(f'  version: {version}')
    lines.append('  contact:')
    lines.append('    name: WAzion Support')
    lines.append('    url: https://www.wazion.com')
    lines.append('    email: support@wazion.com')
    lines.append('  license:')
    lines.append('    name: MIT')
    lines.append('    url: https://opensource.org/licenses/MIT')
    lines.append('')
    lines.append('servers:')
    lines.append('  - url: https://www.wazion.com/api/mcp')
    lines.append('    description: Production')
    lines.append('')
    lines.append('security:')
    lines.append('  - bearerAuth: []')
    lines.append('')
    lines.append('tags:')
    for tl in tag_lines:
        lines.append(tl)

    # Paths section — single MCP endpoint
    lines.append('')
    lines.append('paths:')
    lines.append('  /:')
    lines.append('    post:')
    lines.append('      operationId: jsonRpcRequest')
    lines.append('      summary: JSON-RPC 2.0 endpoint')
    lines.append('      description: |')
    lines.append('        All WAzion API operations go through this single endpoint using JSON-RPC 2.0.')
    lines.append('')
    lines.append('        ### Available methods')
    lines.append('')
    lines.append('        | Method | Auth Required | Description |')
    lines.append('        |--------|--------------|-------------|')
    lines.append('        | `initialize` | No | MCP handshake |')
    lines.append('        | `tools/list` | Yes | List all available tools |')
    lines.append('        | `tools/call` | Yes | Execute a tool |')
    lines.append('        | `resources/list` | Yes | List available resources |')
    lines.append('        | `resources/read` | Yes | Read a resource (e.g. shop://profile) |')
    lines.append('        | `ping` | Yes | Health check |')
    lines.append('')
    lines.append('        ### Tool execution')
    lines.append('')
    lines.append('        Use `tools/call` with `params.name` set to the tool name and `params.arguments`')
    lines.append('        containing the tool parameters.')
    lines.append('')
    lines.append('        ### Confirmations')
    lines.append('')
    lines.append('        Some destructive actions require confirmation. On the first call, the server')
    lines.append('        returns a warning message. Call again with `confirm: true` in the arguments')
    lines.append('        to execute.')
    lines.append('')
    lines.append('        ### Batch requests')
    lines.append('')
    lines.append('        You can send an array of JSON-RPC requests for batch processing.')
    lines.append('      requestBody:')
    lines.append('        required: true')
    lines.append('        content:')
    lines.append('          application/json:')
    lines.append('            schema:')
    lines.append('              oneOf:')
    lines.append("                - $ref: '#/components/schemas/JsonRpcRequest'")
    lines.append('                - type: array')
    lines.append('                  items:')
    lines.append("                    $ref: '#/components/schemas/JsonRpcRequest'")
    lines.append('            examples:')
    lines.append('              initialize:')
    lines.append('                summary: MCP handshake')
    lines.append('                value:')
    lines.append('                  jsonrpc: "2.0"')
    lines.append('                  method: initialize')
    lines.append('                  params:')
    lines.append('                    protocolVersion: "2025-03-26"')
    lines.append('                    capabilities: {}')
    lines.append('                    clientInfo:')
    lines.append('                      name: my-app')
    lines.append('                      version: "1.0.0"')
    lines.append('                  id: 1')
    lines.append('')
    lines.append('              tools_list:')
    lines.append('                summary: List all tools')
    lines.append('                value:')
    lines.append('                  jsonrpc: "2.0"')
    lines.append('                  method: tools/list')
    lines.append('                  params: {}')
    lines.append('                  id: 2')
    lines.append('')
    lines.append('              send_message:')
    lines.append('                summary: Send a WhatsApp message')
    lines.append('                value:')
    lines.append('                  jsonrpc: "2.0"')
    lines.append('                  method: tools/call')
    lines.append('                  params:')
    lines.append('                    name: send_whatsapp_message')
    lines.append('                    arguments:')
    lines.append('                      phone: "+34600000000"')
    lines.append('                      message: "Hello from WAzion API!"')
    lines.append('                      session_id: 1')
    lines.append('                  id: 3')
    lines.append('')
    lines.append('              list_conversations:')
    lines.append('                summary: List recent conversations')
    lines.append('                value:')
    lines.append('                  jsonrpc: "2.0"')
    lines.append('                  method: tools/call')
    lines.append('                  params:')
    lines.append('                    name: get_recent_conversations')
    lines.append('                    arguments:')
    lines.append('                      limit: 10')
    lines.append('                  id: 4')
    lines.append('      responses:')
    lines.append("        '200':")
    lines.append('          description: JSON-RPC response')
    lines.append('          content:')
    lines.append('            application/json:')
    lines.append('              schema:')
    lines.append("                $ref: '#/components/schemas/JsonRpcResponse'")
    lines.append("        '401':")
    lines.append('          description: Missing or invalid Bearer token')
    lines.append("        '405':")
    lines.append('          description: Method not allowed (only POST accepted)')
    lines.append('')
    lines.append('components:')
    lines.append('  securitySchemes:')
    lines.append('    bearerAuth:')
    lines.append('      type: http')
    lines.append('      scheme: bearer')
    lines.append('      description: API token from WAzion Dashboard > Settings')
    lines.append('')
    lines.append('  schemas:')
    lines.append('    JsonRpcRequest:')
    lines.append('      type: object')
    lines.append('      required: [jsonrpc, method, id]')
    lines.append('      properties:')
    lines.append('        jsonrpc:')
    lines.append('          type: string')
    lines.append('          enum: ["2.0"]')
    lines.append('        method:')
    lines.append('          type: string')
    lines.append('          enum: [initialize, tools/list, tools/call, resources/list, resources/read, ping]')
    lines.append('        params:')
    lines.append('          type: object')
    lines.append('        id:')
    lines.append('          oneOf:')
    lines.append('            - type: string')
    lines.append('            - type: integer')
    lines.append('')
    lines.append('    JsonRpcResponse:')
    lines.append('      type: object')
    lines.append('      properties:')
    lines.append('        jsonrpc:')
    lines.append('          type: string')
    lines.append('          enum: ["2.0"]')
    lines.append('        result:')
    lines.append('          description: Success payload (present on success)')
    lines.append('        error:')
    lines.append('          type: object')
    lines.append('          properties:')
    lines.append('            code:')
    lines.append('              type: integer')
    lines.append('            message:')
    lines.append('              type: string')
    lines.append('            data: {}')
    lines.append('          description: Error payload (present on failure)')
    lines.append('        id:')
    lines.append('          oneOf:')
    lines.append('            - type: string')
    lines.append('            - type: integer')
    lines.append('')

    # Tools reference section
    lines.append('    # ── Tool Schemas ──────────────────────────────────')
    lines.append('')

    for tool in tool_schemas:
        schema_name = ''.join(w.capitalize() for w in tool['name'].split('_')) + 'Args'
        lines.append(f"    {schema_name}:")
        lines.append(f"      description: |")
        lines.append(f"        **{tool['name']}** [{tool['category']}] ({tool['type']})")
        desc_line = tool['description'].replace('\n', ' ').strip()
        lines.append(f"        {desc_line}")
        if tool['confirmation']:
            lines.append(f"        ⚠️ Requires confirmation")
        lines.append(f"      type: object")

        if tool['properties']:
            lines.append(f"      properties:")
            for pname, pdef in tool['properties'].items():
                ptype = pdef.get('type', 'string')
                lines.append(f"        {pname}:")
                lines.append(f"          type: {ptype}")
                if 'description' in pdef:
                    pdesc = pdef['description'].replace('\n', ' ').strip()
                    lines.append(f"          description: \"{pdesc}\"")
                if 'enum' in pdef:
                    lines.append(f"          enum: {json.dumps(pdef['enum'])}")
                if 'default' in pdef:
                    lines.append(f"          default: {json.dumps(pdef['default'])}")

            if tool['required']:
                lines.append(f"      required: {json.dumps(tool['required'])}")
        lines.append('')

    return '\n'.join(lines)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <capabilities.json>", file=sys.stderr)
        sys.exit(1)

    caps = load_capabilities(sys.argv[1])

    # Generate tools catalog
    catalog = generate_tools_catalog(caps)
    catalog_path = os.path.join(REPO_ROOT, 'docs', 'tools-catalog.md')
    with open(catalog_path, 'w', encoding='utf-8') as f:
        f.write(catalog)
    print(f"✓ Generated {catalog_path}")

    # Generate partial OpenAPI
    openapi = generate_openapi_yaml(caps)
    openapi_path = os.path.join(REPO_ROOT, 'website', 'static', 'openapi.yaml')
    with open(openapi_path, 'w', encoding='utf-8') as f:
        f.write(openapi)
    print(f"✓ Generated {openapi_path}")

    # Summary
    actions = caps.get('actions', {})
    visible = {k: v for k, v in actions.items() if not v.get('mcp_hidden', False)}
    print(f"  Tools: {len(visible)} (v{caps.get('version', '?')})")


if __name__ == '__main__':
    main()
